### ISSUE TITLE
iOS: Improve Database connection?

### ISSUE THREAD

**Issue by Stophface** [Stophface/react-native-maps-0.20.1#15]
Currently the database connection is opened for every tile. That produces overhead. It makes more sense to open the database connection only once and store this connection somewhere and pass it down to the methods that need it.

**Comment by h3ll0w0rld123** [comment]
I would not worry about this for now, since db connection pooling might get complicated--but again, this is coming from no iOS experience haha. 

Unless you have evidence that it is a performance issue, I'd punt on this to get it easier to merge. I actually, personally, don't think it's an issue, since I believe there is some caching after a tile is loaded (at least that's what it looks like). And I believe the overhead of a local sql connection and query is much, much less than that of an independent http network request, which is my understanding of the urltile.

**Comment by Stophface** [comment]
@h3ll0w0rld123 I personally don't think its a problem - but its just cleaner code and avoids unnecessary strain on the hardware ;-)
